# Generated by Django 2.1.7 on 2019-04-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='班级id')),
            ],
            options={
                'verbose_name_plural': '班级',
                'verbose_name': '班级',
            },
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('collage_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学院id')),
                ('collage_name', models.CharField(max_length=50, verbose_name='学院名称')),
            ],
            options={
                'verbose_name_plural': '学院',
                'verbose_name': '学院',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='课程编码')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('period', models.CharField(max_length=50, verbose_name='课程学时')),
                ('cridit', models.CharField(max_length=50, verbose_name='课程学分')),
                ('course_type', models.IntegerField(verbose_name='课程类型')),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Collage')),
            ],
            options={
                'verbose_name_plural': '课程',
                'verbose_name': '课程',
            },
        ),
        migrations.CreateModel(
            name='curriculum',
            fields=[
                ('curr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='开课id')),
                ('place', models.CharField(max_length=50, verbose_name='地点')),
                ('time', models.CharField(max_length=50, verbose_name='时间')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Course')),
            ],
            options={
                'verbose_name_plural': '已开课程',
                'verbose_name': '已开课程',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='年级编码')),
                ('grade', models.CharField(max_length=50, verbose_name='年级')),
            ],
            options={
                'verbose_name_plural': '年级',
                'verbose_name': '年级',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='专业编码')),
                ('major_name', models.CharField(max_length=50, verbose_name='专业名称')),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Collage')),
            ],
            options={
                'verbose_name_plural': '专业',
                'verbose_name': '专业',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mate_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='资料id')),
                ('mate_name', models.CharField(max_length=50, verbose_name='资料名称')),
                ('end', models.CharField(max_length=50, verbose_name='文件类型')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Course')),
            ],
            options={
                'verbose_name_plural': '资料',
                'verbose_name': '资料',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='职工号')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Collage')),
            ],
            options={
                'verbose_name_plural': '职工',
                'verbose_name': '职工',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Major'),
        ),
    ]
